version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    command: npm start
    ports:
      - '4000:4000'
  frontend:
    build: ./frontend
    container_name: frontend_c
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
  
